### ISSUE TITLE
Printing Country Full Name

### ISSUE THREAD

**Issue by andyslack** [Ghrehh/vue-world-map#10]
Hi There,

I love the plugin but would like the option to print the full country name rather than the country_code in the view.

Is there a way to do this or to support the passing of the full country name instead? 

I think showing the full name rather than the ISO will be clearer for my visitors. 

Thanks.

[
<img width="398" alt="Screenshot 2021-01-25 at 16 31 45" src="https://user-images.githubusercontent.com/3747768/105727114-0827f180-5f2b-11eb-81da-d5796032f5d7.png">
<img width="415" alt="Screenshot 2021-01-25 at 16 32 19" src="https://user-images.githubusercontent.com/3747768/105727119-09591e80-5f2b-11eb-8293-9543870b80fc.png">

](url)

**Comment by noeGnh** [comment]
Just published interactive SVG map component for Vue 3 (world, continents, countries), try it: https://github.com/noeGnh/vue3-map-chart
